name: Build debug
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}
      - name: version patch
        id: version_patch
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_PATCH'
      - name: version code
        id: version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
      - name: version build
        id: version_build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'

      - name: new version patch
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        id: new_version_patch
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_patch.outputs.value }} + 1" | bc)"
      - name: new version code
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        id: new_version_code
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_code.outputs.value }} + 1" | bc)"
      - name: new version build
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        id: new_version_build
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_build.outputs.value }} + 1" | bc)"

      - name: Update version patch
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_PATCH'
          value: ${{ steps.new_version_patch.outputs.value }}
      - name: Update version code
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
          value: ${{ steps.new_version_code.outputs.value }}
      - name: Update version build
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'
          value: ${{ steps.new_version_build.outputs.value }}

      - name: Build all artifacts
        id: buildAllApks
        run: ./gradlew build assembleDebug bundleDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


      #- name: Run Unit Tests with emulator
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    target: default
      #    arch: x86
      #    profile: Nexus 6
      #    script: ./gradlew connectedCheck --stacktrace

      - name: apk_name
        id: apk_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/debug/output-metadata.json)"

      - name: bundle_name
        id: bundle_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/debug/output-metadata.json|sed 's/.apk/.aab/')"

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.apk_name.outputs.file_name}}
          path: app/build/outputs/apk/debug/${{steps.apk_name.outputs.file_name}}

      - name: Upload our Bundle
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.bundle_name.outputs.file_name}}
          path: app/build/outputs/bundle/debug/app-debug.aab

      - name: Upload lint report
        uses: actions/upload-artifact@master
        with:
          name: 'lint-results.html'
          path: app/build/reports/lint-results.html


      #- name: Push new files back to branch.
      #  if: "!contains(github.event.head_commit.message, 'skip-ci')"
      #  uses: stefanzweifel/git-auto-commit-action@v4.11.0
      #  with:
      #    commit_message: "Build version bump, #skip-ci"
      #    status_options: '--untracked-files=no'
      #    disable_globbing: true



